# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a02444e85f023ecb78ed7d2c28195a26dd9dca325a52cf30ddc558bc7f9c8b4572012af7bd493e300e6acf9abcd54cd160b27ae451996dfb01382e0031274a5

test:
  secret_key_base: 3d56e912744cbebcd60e23173c0976029ab544f146d7ba21aa3c12e6c17b82cc2accbc75eba95ea6b3f801ac153d3622add20fed832bccd71ddedde38cc47cd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
